### ISSUE TITLE
Temp build folder for toolchain compilation conflict on shared computer

### ISSUE THREAD

**Issue by paulmnt** [sld-columbia/esp#110]
**Is your feature request related to a problem? Please describe.**
On a shared computer, multiple users cannot build the RISC-V toolchain because of a conflict with the temporary folder `/tmp/_riscv_build`.

**Describe the solution you'd like**
Generate a different temporary folder when running the script to resolve the conflict.

**Describe alternatives you've considered**
Have the script delete the temporary folder when it exists. This solution could work, however, it would prevent concurrent executions and it may fail in case a step of the script exists with an error due to missing system packages.

**Comment by davide-giri** [comment]
How about going back to having the temporary `_riscv_build` and `_leon3_build` folders local in each user's home folder?

**Comment by paulmnt** [comment]
that's an option of course.

**Comment by davide-giri** [comment]
Fixed with PR #119.
