### ISSUE TITLE
Error building the RISCV and Leon3 toolchains

### ISSUE THREAD

**Issue by JuanEsco063** [sld-columbia/esp#131]
**Describe the bug**
The build process fails and exits with errors when reaching the  buildroot install step for both the Leon3 and RISCV installation. 

Before it fails, I get a warning regarding how to handle pulling without specifying how to reconcile divergent branches.

For example, for the Leon3 toolchain I get:

... Linux uClibC tool chain w/ buildroot ... ***
Skip Linux toolchain [y|n]? n: 
Updated 0 paths from the index
hint: Pulling without specifying how to reconcile divergent branches is
hint: discouraged. You can squelch this message by running one of the following
hint: commands sometime before your next pull:
hint: 
hint:   git config pull.rebase false  # merge (the default strategy)
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint: 
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.

**To Reproduce**
1. Run ./utils/toolchain/build_leon3_toolchain.sh or ./utils/toolchain/build_riscv_toolchain.sh 
2. Proceed with the installation as intended
3. When reaching the buildroot step it should give a warning regarding pulling without specifying how to reconcile divergent branches.
4. Continuing with the install yields the error (for example for the Leon3 toolchain):
make: *** No rule to make target '/tmp/_leon3_build/buildroot/output/.br-external.mk'. Stop. 

**Expected behavior**
Both commands finish without error and install the RISCV and Leon3 toolchains. 

**Screenshots**

![Screen Shot 2021-10-28 at 8 49 21 PM](https://user-images.githubusercontent.com/70769188/139356307-33be72ab-464b-42b2-8fe0-83bd192d4ec2.png)
![Screen Shot 2021-10-28 at 8 50 29 PM](https://user-images.githubusercontent.com/70769188/139356310-35d37740-246a-4dda-9c12-a18bd3f33321.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu Desktop 21.04
 - CAD tools versions: Vivado 2019.2

**Comment by JuanEsco063** [comment]
I was unable to build the toolchains even after trying all your suggestions. I decided it would be easier to install Ubuntu 18.04. Let me know if at some point you want to try making things work with a more recent version of Ubuntu and I will be more than happy to help test that.

**Comment by klchiu** [comment]
We will try to support the later version of Ubuntu. Thanks Juan
