### ISSUE TITLE
ESP configuration GUI not opening: 

### ISSUE THREAD

**Issue by mayank-kabra2001** [sld-columbia/esp#141]
Steps - 
# Move to the Xilinx VC707 working folder
cd <esp>/socs/xilinx-vc707-xc7vx485t
make esp-xconfig

Error facing - 
Running interactive ESP configuration...
X11 connection rejected because of wrong authentication.
X11 connection rejected because of wrong authentication.
Traceback (most recent call last):
  File "/home/espuser/esp/tools/socgen/esp_creator.py", line 268, in <module>
    root = Tk()
  File "/usr/lib/python3.6/tkinter/__init__.py", line 2023, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: couldn't connect to display "localhost:10.0"
/home/espuser/esp/utils/make/esp.mk:47: recipe for target 'esp-xconfig' failed
make: *** [esp-xconfig] Error 1

Screenshot - 
![image](https://user-images.githubusercontent.com/57330493/150316402-35d5ab5a-31a4-4868-8298-a47fc84cb8b7.png)

Help Required !!

**Comment by klchiu** [comment]
Hi it seems like a display issue. Are you using a remote server? You can test with xclock to make sure you have the correct X11 forwarding settings

**Comment by mayank-kabra2001** [comment]
Yes I am using the docker on the remote server. I am able to establish X11 connection in the server but not in the docker. 
![image](https://user-images.githubusercontent.com/57330493/150322912-e1112625-881c-4f4f-b9c7-d59f848d6200.png)

**Comment by SaltedFishLZ** [comment]
Hi, Mayank. Could you please try to `sudo bash` to switch to the root user?
I also found this issue. As root, I can open GUI applications.

**Comment by SaltedFishLZ** [comment]
BTW, is it possible to run as a non-root user to show GUI applications in podman (I am using RHEL 8)? @klchiu

**Comment by klchiu** [comment]
Hi @SaltedFishLZ  sorry I just read the message. You shouldn't need to be sudo user to open the GUI. I've never used podman but I can try to see what I can do in the next few weeks

**Comment by TrungNgoc20172869** [comment]
> Steps -
> 
> # Move to the Xilinx VC707 working folder
> cd /socs/xilinx-vc707-xc7vx485t make esp-xconfig
> 
> Error facing - Running interactive ESP configuration... X11 connection rejected because of wrong authentication. X11 connection rejected because of wrong authentication. Traceback (most recent call last): File "/home/espuser/esp/tools/socgen/esp_creator.py", line 268, in root = Tk() File "/usr/lib/python3.6/tkinter/**init**.py", line 2023, in **init** self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use) _tkinter.TclError: couldn't connect to display "localhost:10.0" /home/espuser/esp/utils/make/esp.mk:47: recipe for target 'esp-xconfig' failed make: *** [esp-xconfig] Error 1
> 
> Screenshot - ![image](https://user-images.githubusercontent.com/57330493/150316402-35d5ab5a-31a4-4868-8298-a47fc84cb8b7.png)
> 
> Help Required !!


Hi @klchiu and @mayank-kabra2001, I also have the problems of GUI start like this. How try to run `sudo make esp-xconfig` but it requires espuser password and I dont know what it is. Could you tell me how to fix this?

**Comment by klchiu** [comment]
Hi @TrungNgoc20172869 the password for espuser should be espuser. But I think your problem is about the Xforwarding. When you start the docker container, do you set the DISPLAY variable?
