### ISSUE TITLE
make sim not running 

### ISSUE THREAD

**Issue by mayank-kabra2001** [sld-columbia/esp#142]
Attaching screenshot of error that rtl simulation not running.

![image](https://user-images.githubusercontent.com/57330493/150651744-5c60bdce-e25f-47d7-a72a-227aad95befe.png)

i didnt get why we need to install vivado? It should already be there in the docker. 

Help required!!

**Comment by jzuckerman** [comment]
Hello! The docker image doesn't come with any of the CAD tools installed. Please see instructions on using CAD tools with Docker here: https://esp.cs.columbia.edu/docs/setup/docker/#cad-tools-with-docker

**Comment by mayank-kabra2001** [comment]
Hi , I want to install toolchains mentioned in the https://esp.cs.columbia.edu/docs/setup/setup-guide/#cad-tools. What is the password of espuser ? Am I doing something wrong ? 

![image](https://user-images.githubusercontent.com/57330493/150796036-1768ef92-3d48-47bd-b2de-0359adbabad4.png)

**Comment by mayank-kabra2001** [comment]
Got it!! its default only.. Thanks!!

**Comment by mayank-kabra2001** [comment]
One more question !! If I open the docker with a volume using this command. 

 sudo docker run -it --user espuser --security-opt label=type:container_runtime_t --network=host -e DISPLAY=$DISPLAY -v my-vol:/shared-volume --name my-container-02 columbiasld/esp:ubuntu18-full /bin/bash

It will open for the first time , then after that it will show this error - 
![image](https://user-images.githubusercontent.com/57330493/150906449-d35bdc0d-beb9-4b1e-89c5-481e6d28b9fa.png)

Now if I close this container or start the new container, the toolchain that I installed is gone !! Is there any way to solve this issue ?

**Comment by jzuckerman** [comment]
Once you open a docker container and exit it, you can re-open the session with 
`docker attach <container-ID>`
You can find the container-ID with:
`docker ps -a` 
Checkout other useful commands at the bottom of the Docker setup guide: https://esp.cs.columbia.edu/docs/setup/docker/

**Comment by mayank-kabra2001** [comment]
Ohh got it !! Thanks !!

**Comment by mayank-kabra2001** [comment]
I have install modelsim and Vivado both on my system. Now in esp_env_cad.sh when I want to change my environment variables, it works good for modelsim but not vivado. 

Changes in esp_env_cad.sh - 

![WhatsApp Image 2022-01-26 at 3 11 11 PM](https://user-images.githubusercontent.com/57330493/151139764-864b0a25-b614-45ac-a3c9-9698c1dbd30b.jpeg)

Error - 

![WhatsApp Image 2022-01-26 at 3 08 48 PM](https://user-images.githubusercontent.com/57330493/151139914-8b19db64-fe2e-4ea9-a4bc-7ba72131b1bb.jpeg)

I can still source it in my system, which means that it is working correct - 

![WhatsApp Image 2022-01-26 at 3 08 25 PM](https://user-images.githubusercontent.com/57330493/151140041-823396b4-8042-41b6-a73a-f23bd06223ec.jpeg)


Help Required !!

**Comment by mayank-kabra2001** [comment]
After resolving this sourcing issue - I am getting this error - 
![image](https://user-images.githubusercontent.com/57330493/151170774-02075ece-f07d-4cd3-b797-b0603dc08cb3.png)

Help Required!!

**Comment by jzuckerman** [comment]
It looks like in your `esp_env_cad.sh`, you have the command that adds the modelsim to your PATH variable commented out (the first line under the Mentor section). You need this line for modelsim to be found.

**Comment by mayank-kabra2001** [comment]
That is the license of modelsim. Do we really need that?

**Comment by jzuckerman** [comment]
Looks like modelsim can't find the expected libraries from Xilinx. Please note that ESP supports Vivado version 2019.2, and I see that you are using Vivado 2020.1.

**Comment by mayank-kabra2001** [comment]
Hi, 

I tried to install Vivado 2019.2 and then check, its still showing the errors. 
One question - Do we need to have licenses for Both Xilinx and modelsim ? 

Thanks.

**Comment by TrungNgoc20172869** [comment]
> Hi , I want to install toolchains mentioned in the https://esp.cs.columbia.edu/docs/setup/setup-guide/#cad-tools. What is the password of espuser ? Am I doing something wrong ?
> 
> ![image](https://user-images.githubusercontent.com/57330493/150796036-1768ef92-3d48-47bd-b2de-0359adbabad4.png)

Hi, I am facing the same issue and dont know what the password is. Could you tell me the espuser password ?
