### ISSUE TITLE
Issue with hls4ml baremetal flow 

### ISSUE THREAD

**Issue by mayank-kabra2001** [sld-columbia/esp#150]
Hi, I observed that after doing SoC configuration of hls4ml accelerator, when I tried make mlp3layers_hls4ml-baremetal, I got this error. 
![image](https://user-images.githubusercontent.com/57330493/155469542-c984d13b-c33c-4fc8-a7e1-26855bb97951.png)

This issue is resolved by updating the esp-probe.h and mlp3layers.c
mlp3layers.c - #define fl2fx(A) float_to_fixed32(A, INT_BITS) 
esp-probe.h - ndev = probe(&espdevs, SLD_MLP3LAYERS, DEV_NAME);

Hope this is the only thing what I need to do. 
Thanks!!

**Comment by jzuckerman** [comment]
Did you fix this? You should be able to fix it by adding a VENDOR_SLD argument before the SLD_MLP3LAYERS argument.

**Comment by mayank-kabra2001** [comment]
I removed the argument from .h file itself and it worked .
