### ISSUE TITLE
Missing submodule in QEMU repository while installing RISC-V 64-bit (Ariane) toolchain

### ISSUE THREAD

**Issue by JuanEsco063** [sld-columbia/esp#164]
It seems one of the submodules, qemu-palcode specifically, of the qemu repository has been moved or is somehow broken.

I am following the steps from the setup tutorial and the error appears when I run the command to install the risc-v 64-bit Ariane toolchain:

./utils/toolchain/build_riscv_toolchain.sh

Here is a screenshot of the error I get:
![Screen Shot 2022-06-17 at 1 26 05 PM](https://user-images.githubusercontent.com/70769188/174348410-2833d885-1333-4230-afaa-cb90a5d68b3d.png)

I am running this on Ubuntu 20.04 LTS. I installed the toolchains without issue before so I doubt this is affecting it.

**Comment by jzuckerman** [comment]
Hi Juan, 

I've run into this issue as well. I'm not sure why this repo doesn't want to download through our script anymore. Here is a manual fix while I look into a more permanent one:

1. go to `${ESP_ROOT}/_risv_build/riscv-gnu-toolchain/riscv-qemu/roms/`
2. clone the repo that is failing directly from here https://github.com/rth7680/qemu-palcode
3. comment out lines 102 and 103 `${ESP_ROOT}/utils/toolchain/build_riscv_toolchain.sh` to avoid removing the temporary directory
4. rerun the toolchain

Let me know if you have further issues.

**Comment by JuanEsco063** [comment]
Let me try that. 

What I noticed is the URL for the QEMU submodule in the .gitmodule file in the riscv-gnu-toolchain repo points to https://git.qemu.org/git/qemu.git however, if you go to that site using a browser, you are automatically redirected to https://gitlab.com/qemu-project/qemu . Maybe the script or git are not redirecting automatically.

**Comment by JuanEsco063** [comment]
@jzuckerman Following your steps resolved the issue. Would it be best for me to close the issue or leave it open until the script is fixed?

**Comment by JuanEsco063** [comment]
@jzuckerman I am installing ESP on another computer (rather, a docker container ) and while installing the RISCV toolchain I am getting the following error:

![Screen Shot 2022-06-29 at 1 37 06 PM](https://user-images.githubusercontent.com/70769188/176500538-a7e109b7-087f-4947-ad27-fda19b16d7c0.png)

This is after applying the workaround you mentioned for the QEMU repo.

**Comment by jzuckerman** [comment]
Let's leave the issue open until there's a permanent fix. 

Not sure about the new error. What's the OS of this machine? Are there any helpful details in config.log?

**Comment by mayank-kabra2001** [comment]
Is this issue resolved now ?

**Comment by JuanEsco063** [comment]
Not that I am aware.  I'm still doing the workaround suggested by Joseph.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by mayank-kabra2001** [comment]
No, i tried the workaround but it didnt work for me ..

**Comment by JuanEsco063** [comment]
Can you post more details about where it fails for you?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jzuckerman** [comment]
Sorry for the delay here. The following two commands should resolve this issue. I'll include them as a part of the toolchain.
```
git config --global url.https://github.com/qemu/.insteadOf git://git.qemu-project.org/
git config --global url.https://anongit.freedesktop.org/git/.insteadOf git://anongit.freedesktop.org/
```
