### ISSUE TITLE
Replace polling with interrupt in RISC-V device driver

### ISSUE THREAD

**Issue by paulmnt** [sld-columbia/esp#17]
The initial integration of Ariane did not support distributed interrupts. Therefore, the ESP device driver is currently polling the accelerator's status register to check for completion.

Now that distributed interrupts are supported, we can switch to using interrupts for ESP accelerators.

This update should be applied to <esp>/soft/ariane/drivers/esp/esp.c

**Comment by davide-giri** [comment]
Done and tested on FPGA. Now Ariane waits for the interrupt from the accelerator in the same way as the Leon3.
