### ISSUE TITLE
Alternatives of listed FPGA boards

### ISSUE THREAD

**Issue by OlinLai** [sld-columbia/esp#209]
When I wanted to go through the tutorial, I found that I have to use an FPGA development board.

The homepage lists FPGA development boards that support the ESP framework as follows

*FPGA development boards
Xilinx Virtex UltraScale+ FPGA VCU118 and VCU128
Xilinx Virtex-7 FPGA VC707
proFPGA [Virtex7 XC7V2000T FPGA]
proFPGA [Virtex Ultrascale XCVU440 FPGA]

Can other (inexpensive) FPGA development boards be used as alternatives? If so, which boards can be used?

**Comment by jzuckerman** [comment]
The comments in issue #68 describes the requirements and steps for adding support for a new FPGA. At this time, we do not have plans to add support for any additional platforms, but it is possible if the requirements are met, and we welcome external contributions. Please let me know if you have any additional questions.
