### ISSUE TITLE
Bootloader hangs on ESP soc includes nvdla on VCU128

### ISSUE THREAD

**Issue by mahmed1986** [sld-columbia/esp#220]
**Describe the bug**
I  am using fpga board vcu128. I want to build esp soc with nvdla. I followed that link  (https://www.esp.cs.columbia.edu/docs/thirdparty_acc/thirdparty_acc-guide/). I know it  is tested on vcu118. but I think it should be working with vcu128. linux doesn boot and stopped at bootloader

![image](https://github.com/sld-columbia/esp/assets/167722921/cdd16eda-1a72-4577-ad95-efa5aa26499f)

I tried to create hardware based on default config using   make esp-defconfig and created bitstream + image. I can boot image succefully. 

I tried to using the linux image created by default config with bitstream of nvdla config ( I know drivers and device tree is different). I tested reading read only  HW version resgisters of nvdla cores using devmem. I can read it succeffuly as expected  

My question, how to debug hang issue of linux doesn't boot. any suggestions. 
#

**To Reproduce**
following guide https://www.esp.cs.columbia.edu/docs/thirdparty_acc/thirdparty_acc-guide/ but on vcu128.
 

**Expected behavior**
linux boots

**Screenshots**
linux doesn't boot : ![image](https://github.com/sld-columbia/esp/assets/167722921/414ec07f-7c22-46b4-89c5-84e08ff20bd3)

**Desktop (please complete the following information):**
 - ubunut 18.04

**Additional context**

**Comment by jzuckerman** [comment]
Based on the print at the top of your screen (`random: crng init done`). It seems like you were able to boot Linux before. Is this correct and you were not able to reboot? If this is the case, be sure to run `make fpga-program` before rerunning `make fpga-run-linux`. Only running `make fpga-run-linux` does not apply a full reset to the SoC, so the boot is not guaranteed to work without programming first.
