### ISSUE TITLE
Centos 7 update broke the binutils step of the Leon3 toolchain initialization

### ISSUE THREAD

**Issue by davide-giri** [sld-columbia/esp#24]
Due to some recent CentOS 7 update the `binutils` step of the Leon3 toolchain initialization: `utils/scrips/build_leon3_toolchain.sh`.

**Comment by paulmnt** [comment]
We solved the issue by upgrading the toolchain. Now we compile both the tool chain and the root file system with buildroot.
In doing so we've also improved the init scripts to get the root password set automatically and obtain a DHCP IP without running commands on the UART console.
