### ISSUE TITLE
Red Hat 7.x

### ISSUE THREAD

**Issue by GiuseppeDiGuglielmo** [sld-columbia/esp#40]
**Describe the bug**

You can run the ESP flow on Red Hat 7.8. Add the following command to the [Centos 7 instructions](https://www.esp.cs.columbia.edu/docs/setup/setup-guide/).

```
sudo yum install http://mirror.centos.org/centos/7/extras/x86_64/Packages/dtc-1.4.6-1.el7.x86_64.rpm
```

I couldn't find a native package for DTC, so I opted for the rpm package on the Centos 7 repository.

**Comment by paulmnt** [comment]
Instruction on how to setup ESP with Red Hat are now available: [setup guide](https://esp.cs.columbia.edu/docs/setup/setup-guide/#red-hat-enterprise-linux-78)
