### ISSUE TITLE
Need to change the shell file address when install software toolchains.

### ISSUE THREAD

**Issue by AltiumHanChou** [sld-columbia/esp#96]
**Describe the bug**
Need to change the shell file address when install software toolchains.

**To Reproduce**

> 1. `cd <esp root>/esp`
> 2. ` (echo y; echo <root>/ESP_Platform/leon; echo 2; echo n; echo n; echo n; echo n) | bash utils/toolchain/build_leon3_toolchain.sh && rm -rf /tmp/_leon3_build`
> 3.  `(echo y; echo <root>/ESP_Platform/riscv; echo 2; echo n; echo n; echo n) | bash utils/toolchain/build_riscv_toolchain.sh && rm -rf /tmp/_riscv_build `
> 4. ` (echo y; echo <root>/ESP_Platform/riscv32imc; echo 2; echo n) | bash utils/toolchain/build_riscv32imc_toolchain.sh && rm -rf /tmp/_riscv32imc_build `
> 

**Error log**

> ```
> *** This script will build and install the leon tool chain for Leon3 ***
> *** Installing to <root>/ESP_Platform/leon ... ***
> *** Installing bare-metal compiler... ***
> --2021-03-25 06:49:20--  http://espdev.cs.columbia.edu/stuff/leon3/sparc-elf-4.4.2.tar
> Resolving espdev.cs.columbia.edu (espdev.cs.columbia.edu)... 128.59.20.230
> Connecting to espdev.cs.columbia.edu (espdev.cs.columbia.edu)|128.59.20.230|:80... failed: Connection timed out.
> Retrying.
> ```
> It has connection error when I install leon3 software toolchains.
> (This log also happen on  riscV & riscV32mic)

**Solution**

> Go into the following file : 
> `utils/toolchain/build_leon3_toolchain.sh`
> `utils/toolchain/build_riscv_toolchain.sh`
> `utils/toolchain/build_riscv32imc_toolchain.sh`
> Please find the variable `SRC_MIRROR`, and modify it's value to`https://espdev.cs.columbia.edu/stuff/....`  (`http`  to `https`).

**Comment by paulmnt** [comment]
Yes, that’s correct: our IT team asked us to switch to https on all web servers that we run last week. We will update the URL in the script ASAP.
Thank you again!
